# Configuración básica
title: CoderH JS
description: Mi sitio Jekyll de CoderH JS
baseurl: ""
url: ""

# Configuración del tema
theme: jekyll-theme-primer

# Otras configuraciones opcionales
plugins:
  - jekyll-feed
  - jekyll-seo-tag